#pragma once

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 4
#define OLED_TIMEOUT 360000
#define OLED_DISPLAY_WIDTH 128
#define OLED_DISPLAY_HEIGHT 32
#define RGB_MATRIX_KEYPRESSES
